CREATE TABLE parking_lots
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source             VARCHAR(30)  NOT NULL,
    source_external_id VARCHAR(40)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    sido               VARCHAR(30),
    sigungu            VARCHAR(30),
    address            VARCHAR(255),
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    capacity           INTEGER,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    source_checked_at  TIMESTAMPTZ  NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_parking_lots_capacity
        CHECK (capacity IS NULL OR capacity >= 0)
);

CREATE UNIQUE INDEX idx_parking_lots_source_external_id
    ON parking_lots (source, source_external_id);

CREATE INDEX idx_parking_lots_region
    ON parking_lots (sido, sigungu);

CREATE INDEX idx_parking_lots_location
    ON parking_lots (latitude, longitude);

CREATE TABLE parking_operations
(
    parking_lot_id          BIGINT PRIMARY KEY,
    base_free_minutes       INTEGER,
    base_minutes            INTEGER,
    base_fee                INTEGER,
    additional_minutes      INTEGER,
    additional_fee          INTEGER,
    daily_max_fee           INTEGER,
    monthly_fee             INTEGER,

    monday_status           VARCHAR(10),
    monday_open_time        TIME,
    monday_close_time       TIME,
    tuesday_status          VARCHAR(10),
    tuesday_open_time       TIME,
    tuesday_close_time      TIME,
    wednesday_status        VARCHAR(10),
    wednesday_open_time     TIME,
    wednesday_close_time    TIME,
    thursday_status         VARCHAR(10),
    thursday_open_time      TIME,
    thursday_close_time     TIME,
    friday_status           VARCHAR(10),
    friday_open_time        TIME,
    friday_close_time       TIME,
    saturday_status         VARCHAR(10),
    saturday_open_time      TIME,
    saturday_close_time     TIME,
    sunday_status           VARCHAR(10),
    sunday_open_time        TIME,
    sunday_close_time       TIME,
    holiday_status          VARCHAR(10),
    holiday_open_time       TIME,
    holiday_close_time      TIME,

    source_checked_at       TIMESTAMPTZ NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_parking_operations_parking_lot
        FOREIGN KEY (parking_lot_id)
            REFERENCES parking_lots (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_parking_operations_fee_non_negative
        CHECK (
            (base_free_minutes IS NULL OR base_free_minutes >= 0)
                AND (base_minutes IS NULL OR base_minutes >= 0)
                AND (base_fee IS NULL OR base_fee >= 0)
                AND (additional_minutes IS NULL OR additional_minutes >= 0)
                AND (additional_fee IS NULL OR additional_fee >= 0)
                AND (daily_max_fee IS NULL OR daily_max_fee >= 0)
                AND (monthly_fee IS NULL OR monthly_fee >= 0)
        ),

    CONSTRAINT ck_parking_operations_monday_status
        CHECK (monday_status IS NULL OR monday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_tuesday_status
        CHECK (tuesday_status IS NULL OR tuesday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_wednesday_status
        CHECK (wednesday_status IS NULL OR wednesday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_thursday_status
        CHECK (thursday_status IS NULL OR thursday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_friday_status
        CHECK (friday_status IS NULL OR friday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_saturday_status
        CHECK (saturday_status IS NULL OR saturday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_sunday_status
        CHECK (sunday_status IS NULL OR sunday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN')),
    CONSTRAINT ck_parking_operations_holiday_status
        CHECK (holiday_status IS NULL OR holiday_status IN ('OPEN', 'CLOSED', 'ALL_DAY', 'UNKNOWN'))
);
