CREATE TABLE parking_reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detail         VARCHAR(500),
    parking_lot_id BIGINT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_parking_reviews_parking_lot
        FOREIGN KEY (parking_lot_id)
            REFERENCES parking_lots (id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_parking_reviews_parking_lot_id
    ON parking_reviews (parking_lot_id);
