spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:jumin}
spring.datasource.username=${DB_USERNAME:jumin}
spring.datasource.password=${DB_PASSWORD:jumin}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

local-search.base-url=${LOCAL_SEARCH_BASE_URL:https://naverapihub.apigw.ntruss.com}
local-search.client-id=${LOCAL_SEARCH_CLIENT_ID}
local-search.client-secret=${LOCAL_SEARCH_CLIENT_SECRET}
